name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build
      run: gcc -ansi -pedantic -Wall -o pre_assembler pre_assembler.c

    - name: Run tests (if you have any)
      run: |
        echo "No tests yet"